runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon\.ico
  static_files: dist/img/favicon.ico
  upload: dist/images/img\.ico

- url: /fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: dist/bower_components/bootstrap/fonts/\1
  upload: dist/bower_components/bootstrap/fonts/(.*\.eot)

- url: /fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: dist/bower_components/bootstrap/fonts/\1
  upload: dist/bower_components/bootstrap/fonts/(.*\.eot)

- url: /fonts/(.*\.woff)
  mime_type: application/x-font-woff
  static_files: dist/bower_components/bootstrap/fonts/\1
  upload: dist/bower_components/bootstrap/fonts/(.*\.woff)

- url: /fonts/(.*\.woff2)
  mime_type: application/x-font-woff2
  static_files: dist/bower_components/bootstrap/fonts/\1
  upload: dist/bower_components/bootstrap/fonts/(.*\.woff2)
  
- url: /bower_components
  static_dir: dist/bower_components

- url: /css
  static_dir: dist/css

- url: /js
  static_dir: dist/js

- url: /img
  static_dir: dist/img

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
  
skip_files:
- ^node_modules/*
- .git/*
