runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: dist/css

- url: /js
  static_dir: dist/js

- url: /img
  static_dir: dist/img

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
  