runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /css
  upload: ../dist/css/*.css
  static_files: css/\1

- url: /js
  static_dir: ..\dist\js

- url: /img
  static_dir: ../dist/img

libraries:
- name: jinja2
  version: latest
  