runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /css
  static_dir: ../public/css

- url: /js
  static_dir: ../public/js

- url: /img
  static_dir: ../public/img

libraries:
- name: jinja2
  version: latest
  